/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runmit_mediaserver_MediaServer */

#ifndef _Included_com_runmit_mediaserver_MediaServer
#define _Included_com_runmit_mediaserver_MediaServer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_runmit_mediaserver_MediaServer_PORT
#define com_runmit_mediaserver_MediaServer_PORT 8080L
/*
 * Class:     com_runmit_mediaserver_MediaServer
 * Method:    init
 * Signature: (ILjava/lang/String;)I
 */




JNIEXPORT jint JNICALL Java_com_runmit_mediaserver_MediaServer_init
  (JNIEnv *, jclass, jint, jint, jstring);//, jint, jint, jstring, jstring);


JNIEXPORT jint JNICALL Java_com_runmit_mediaserver_MediaServer_setLocalInfo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_runmit_mediaserver_MediaServer
 * Method:    fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runmit_mediaserver_MediaServer_uninit
  (JNIEnv *, jclass);

/*
 * Class:     com_runmit_mediaserver_MediaServer
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runmit_mediaserver_MediaServer_run
  (JNIEnv *, jclass);

/*
 * Class:     com_runmit_mediaserver_MediaServer
 * Method:    getHttpListenPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_runmit_mediaserver_MediaServer_getHttpListenPort
  (JNIEnv *, jclass);

/*
 * Class:     com_runmit_mediaserver_MediaServer
 * Method:    getVodTaskInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_runmit_mediaserver_MediaServer_getVodTaskInfo
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
