package com.runmit.sweedee.datadao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH_HIS_RECORD.
 */
public class SearchHisRecord {

    private String words;
    private Long time;

    public SearchHisRecord() {
    }

    public SearchHisRecord(String words) {
        this.words = words;
    }

    public SearchHisRecord(String words, Long time) {
        this.words = words;
        this.time = time;
    }

    public String getWords() {
        return words;
    }

    public void setWords(String words) {
        this.words = words;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
